// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"golang-project-layout/model/repository/config"
	"golang-project-layout/model/repository/once"
)

// Injectors from wire.go:

func Init(baseConfigFile string) (*Container, error) {
	serviceConfig, err := config.NewServiceConfig(baseConfigFile)
	if err != nil {
		return nil, err
	}
	iOnce, err := once.NewOnce(serviceConfig)
	if err != nil {
		return nil, err
	}
	container := &Container{
		_forbidden: iOnce,
	}
	return container, nil
}

// wire.go:

type Container struct {
	// once config
	_forbidden once.IOnce
}
